apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o2yhxv98d-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:2591c12eb0d4d150fa6c978be39116cd0f952ea3@sha256:e5f93657d5eaa9d3975d676437857fe41f47ca03182ed898b0fac8e76e998eb2
          name: container-image
